import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Concert_One } from "next/font/google";


const font = Concert_One({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
